[build]
  build = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NETLIFY_USE_PYTHON = "false"

[dev]
  command = "astro dev --host"
  port = 8888
  targetPort = 3000